// flow-typed signature: bc2692cacd64f7445d6f0bb3f32cbd61
// flow-typed version: <<STUB>>/copy-pkg_v^1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-pkg/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-pkg/bin.js' {
  declare module.exports: $Exports<'copy-pkg/bin'>;
}
declare module 'copy-pkg/index' {
  declare module.exports: $Exports<'copy-pkg'>;
}
declare module 'copy-pkg/index.js' {
  declare module.exports: $Exports<'copy-pkg'>;
}
