// flow-typed signature: 676687bb8e328f6c9dc75f6e8a71deb0
// flow-typed version: <<STUB>>/styled-tools_v^0.5.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-tools/dist/cjs/ifNotProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/ifProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/prop' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/switchProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/withProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/ifNotProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/ifProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/index' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/prop' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/switchProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/withProp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-tools/dist/cjs/ifNotProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/ifNotProp'>;
}
declare module 'styled-tools/dist/cjs/ifProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/ifProp'>;
}
declare module 'styled-tools/dist/cjs/index.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/index'>;
}
declare module 'styled-tools/dist/cjs/prop.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/prop'>;
}
declare module 'styled-tools/dist/cjs/switchProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/switchProp'>;
}
declare module 'styled-tools/dist/cjs/withProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/withProp'>;
}
declare module 'styled-tools/dist/es/ifNotProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/ifNotProp'>;
}
declare module 'styled-tools/dist/es/ifProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/ifProp'>;
}
declare module 'styled-tools/dist/es/index.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/index'>;
}
declare module 'styled-tools/dist/es/prop.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/prop'>;
}
declare module 'styled-tools/dist/es/switchProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/switchProp'>;
}
declare module 'styled-tools/dist/es/withProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/withProp'>;
}
