// flow-typed signature: 8be706b007ff6a5c420fedaa97692a74
// flow-typed version: <<STUB>>/styled-tools_v^0.4.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-tools/dist/cjs/call' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/ifProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/prop' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/switchProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/types' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/cjs/withProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/call' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/ifProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/index' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/prop' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/switchProp' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/types' {
  declare module.exports: any;
}

declare module 'styled-tools/dist/es/withProp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-tools/dist/cjs/call.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/call'>;
}
declare module 'styled-tools/dist/cjs/ifProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/ifProp'>;
}
declare module 'styled-tools/dist/cjs/index.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/index'>;
}
declare module 'styled-tools/dist/cjs/prop.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/prop'>;
}
declare module 'styled-tools/dist/cjs/switchProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/switchProp'>;
}
declare module 'styled-tools/dist/cjs/types.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/types'>;
}
declare module 'styled-tools/dist/cjs/withProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/cjs/withProp'>;
}
declare module 'styled-tools/dist/es/call.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/call'>;
}
declare module 'styled-tools/dist/es/ifProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/ifProp'>;
}
declare module 'styled-tools/dist/es/index.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/index'>;
}
declare module 'styled-tools/dist/es/prop.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/prop'>;
}
declare module 'styled-tools/dist/es/switchProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/switchProp'>;
}
declare module 'styled-tools/dist/es/types.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/types'>;
}
declare module 'styled-tools/dist/es/withProp.js' {
  declare module.exports: $Exports<'styled-tools/dist/es/withProp'>;
}
